<?php
/**
 *  用户控制器
 * User: @ 若雨PhpSt
 * Date: 2018/9/18
 * Time: 20:22
 */

namespace app\user\controller;
use app\index\controller\BaseController;

class User extends BaseController
{
    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->isLogin();
    }

    // 展示个人中心
    public function member(){
        return $this->fetch();
    }
}